name: 'send-awesome-code-to-slack'
description: '良いコード片をコメントとともにSlackへ投げるのが得意です'
author: 'mofmof'
inputs:
  gitHubToken:
    required: true
    description: 'GitHub Token'
  gitHubEventPath:
    required: true
    description: 'GitHub Event Path'
  slackToken:
    required: true
    description: 'Slack Token'
  slackChannel:
    required: true
    description: 'Slack Channel'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: message-square
  color: green
