name: 'send-awesome-code-to-slack'
description: '良いコード片をコメントとともにSlackへ投げるのが得意です'
author: 'mofmof'
inputs:
  trigger_keyword:
    required: true
    description: 'If you find a keyword in a comment, it will be posted to slack.'
  github_token:
    required: true
    description: 'GitHub Token'
  github_event_path:
    required: true
    description: 'GitHub Event Path'
  slack_token:
    required: true
    description: 'Slack Token'
  slack_channel:
    required: true
    description: 'Slack Channel'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: message-square
  color: green
