name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  gitHubToken:
    required: true
    description: 'GitHub Token'
  gitHubEventPath:
    required: true
    description: 'GitHub Token'

runs:
  using: 'node16'
  main: 'dist/index.js'
