name: 'test'
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          gitHubEventPath: ${{ secrets.GIT_HUB_EVENT_PATH }}
          slackToken: ${{ secrets.SLACK_TOKEN }}
          slackChannel: ${{ secrets.SLACK_CHANNEL }}
